configMapGenerator:
- name: nginx-config
  files:
    - nginx/nginx.conf
- name: telegraf-config
  files:
    - telegraf/telegraf.conf
secretGenerator:
- name: mysql-pass
  literals:
  - password=unicorn
- name: sftp-users
  literals:
  - users=unicorn:unicorn:1001
- name: sftp-host-keys
  files:
  - ssh_host_rsa_key=sftp-keys/ssh_host_rsa_key
  - ssh_host_ed25519_key=sftp-keys/ssh_host_ed25519_key
- name: ssh-host-keys
  files:
  - ssh_host_rsa_key=ssh-keys/ssh_host_rsa_key
  - ssh_host_ed25519_key=ssh-keys/ssh_host_ed25519_key
- name: tls-key
  files:
  - tls.key=tls-keys/tls.key
  - tls.crt=tls-keys/tls.crt
resources:
- nginx.yaml
- mysql.yaml
- wordpress.yaml
- phpmyadmin.yaml
- sftp.yaml
- kubernetes-dashboard.yaml
- ingress.yaml
- grafana.yaml
- influxdb.yaml
- telegraf.yaml
