apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    name: telegraf
spec:
  selector:
    name: telegraf
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      name: telegraf
  template:
    metadata:
      labels:
        name: telegraf
    spec:
      serviceAccountName: telegraf-account
      containers:
      - name: telegraf
        image: telegraf:alpine
        env:
        - name: HOSTNAME
          value: "telegraf-polling-service"
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf
      volumes:
      - name: config
        configMap:
          name: telegraf-config

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: influx:cluster:viewer
  labels:
    rbac.authorization.k8s.io/aggregate-view-telegraf: "true"
rules:
- apiGroups: [""]
  resources:
  - persistentvolumes
  - nodes
  - endpoints
  - deployments
  - services
  - pods
  - statefulsets
  - daemonsets
  - persistentvolumeclaims
  - ingresses
  verbs: ["get", "list"]

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: influx:telegraf
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-view-telegraf: "true"
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-to-view: "true"
rules: []

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: influx:telegraf:viewer
subjects:
- kind: ServiceAccount
  name: telegraf-account
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: influx:telegraf

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf-account
  labels:
    app: telegraf
